[retention]
keep-last = 1
keep-hourly = 0
keep-daily = 7
keep-weekly = 4
keep-monthly = 3
keep-yearly = 1

[[paths]]
path = "/var/backups/consul"
file-pattern = "{name}_{year}-{month}-{day}T{hour}:{minutes}{TZ}.bck"

[[paths]]
path = "/var/backups/upsource"
file-pattern = "{year} {month_name} {day} {hour}-{minutes}-{seconds}"

[[paths]]
path = "/var/backups/hub"
file-pattern = "hub-backup-{year}-{month}-{day}-{hour}-{minutes}-{seconds}.tar.gz"

[[paths]]
path = "/var/backups/pg"
file-pattern = "{year}-{month}-{day}T{hour}:{minutes}{TZ}"
